### ISSUE TITLE
Have you add a look onto ESPEasy to link your work as a plugin ?

### ISSUE THREAD

**Issue by gmella** [xlyric/Pv-router#1]
Salut,

 I plan to setup a PV router on my installation. I like your repo and setup running on ESP.
Quite all of my ESP8266 are running on ESPEasy since it is very easy to connect new devices,defines rules and exchanges data over wifi domoticz included ;).  I just made a PR for a plugin for my Linky reading. During this work I wondered  if you thougth about such idea to include PV router support as a plugin to ESPEasy. Is that the case ?

Anyway, thank you for sharing your work! Merci !
( En fait j'ai modifié le plugin par defaut ADC internal pour garder les valeurs min-max du mode oversampling 50fois par s. Mais c'est pas très précis....)

**Comment by xlyric** [comment]
Salut, 
pour espeasy, j'ai aussi quelques IOT dessus , mais je connais pas leurs systèmes de plugins. 
après perso, j'utilise maintenant plus tasmoda c'est plus simple à configurer.

désolé de pas avoir répondu plus tot, j'avais pas vu que j'avais une issue d'ouverte.
